name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish the Docker image
      run: |
        docker login -u huangtingluo -p ${{secrets.dockerpat}}
        docker build . --file Dockerfile --tag huangtingluo/runner-test:$GITHUB_SHA --tag huangtingluo/runner-test:latest --build-arg RUNNER_REPO="https://github.com/tingluohuang/main" --build-arg RUNNER_TOKEN=${{secrets.runnertoken}}
        docker push huangtingluo/runner-test:$GITHUB_SHA
        docker push huangtingluo/runner-test:latest
